default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: form_uploader_test_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: form_uploader_test_test
  username: postgres
  password: postgres
  
production:
  <<: *default
  database: form_uploader_test_production
  username: postgres
  password: postgres
